# Generated by Django 5.2.7 on 2025-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this time slot (e.g., 'Morning Menu', 'Lunch Menu')", max_length=100)),
                ('start_date', models.DateField(help_text='Start date for menu availability')),
                ('end_date', models.DateField(help_text='End date for menu availability')),
                ('start_time', models.TimeField(help_text='Start time for menu availability')),
                ('end_time', models.TimeField(help_text='End time for menu availability')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this time slot is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu Time Slot',
                'verbose_name_plural': 'Menu Time Slots',
                'ordering': ['-created_at'],
            },
        ),
    ]
